# Generated by Django 4.1.5 on 2023-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubuser', models.CharField(max_length=1000)),
                ('imagelnk', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
            ],
        ),
    ]
