# Generated by Django 4.1.5 on 2023-02-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='imagelnk',
            new_name='imagelink',
        ),
    ]
